env:
  node: true
  commonjs: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
ignorePatterns:
  - migrations/*.js
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
plugins:
  - jest
  - sequelize-node

overrides:
- files:
  - "**/*.test.js"
  env:
    jest: true
