name: Linter

on:
  - push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Linter
        uses: stefanoeb/eslint-action@1.0.2
