name: Linter

env:
  node-version: 16.8.0

on:
  - push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - run: npm install
      - run: npx eslint .
