name: Run specs

env:
  node-version: 16.8.0

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    services:
      db:
        image: postgres:13.0
        env:
          USER: postgres
          password: postgresadmin
          NAME: "tasky_test"
        ports:
        - 5432:5432

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - run: npm ci
      - run: npm test
