name: Run specs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

matrix:
  node-version: 16.8.0

jobs:
  build:
    run-on: ubuntu-latest
    environment: test

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        run: npm ci
        run: npm test
